[tool.poetry]
name = "whiscribe"
version = "0.2.0"
description = "A tool with a UI that transcribes audio files into subtitles using OpenAI's Whisper."
authors = ["silentsoft <hyesung.lee@silentsoft.org>"]
readme = "README.md"

[tool.poetry.dependencies]
python = ">=3.10,<4.0"
flet = {extras = ["all"], version = "^0.84.0"}
ffmpeg-python = "^0.2.0"
whisper-timestamped = "^1.15.9"

[tool.poetry.group.dev.dependencies]
pytest = "^8.3.3"

[tool.poetry.scripts]
whiscribe = "cli:launch"
build = "cli:build"

[tool.flet]
product = "Whiscribe"
artifact = "Whiscribe"
org = "org.silentsoft"
bundle_id = "org.silentsoft.whiscribe"
company = "silentsoft.org."
copyright = "Copyright © silentsoft.org"

[tool.flet.macos]
target_arch = ["arm64"]

[tool.flet.macos.app]
exclude = ["__pycache__", "whiscribe/__pycache__", "cli.py", "bin/ffmpeg.exe", "bin/ffprobe.exe"]

[tool.flet.windows.app]
exclude = ["__pycache__", "whiscribe/__pycache__", "cli.py", "bin/ffmpeg", "bin/ffprobe"]

[tool.flet.app]
path = "src"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
